# Generated by Django 4.2.10 on 2024-02-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhd_planner_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addathingtodo',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
